const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(require('node:url').pathToFileURL(require('node:path').resolve('bfit-admin/index.html')).href);
assert.equal(await page.locator('fieldset').count(),24);
assert.equal(await page.locator('#setup').isVisible(),false);
await page.locator('#next').click();assert.match(await page.locator('#step-text').innerText(),/Paso 1/);
await page.locator('[name="Nombre"]').fill('PRUEBA TÉCNICA J49');
await page.locator('[name="email"]').fill('qa@example.com');
await page.locator('#sections button').nth(2).click();
await page.locator('[data-q="7"] button').last().click();
assert.equal(await page.locator('[data-q="7"] .repeat-row').count(),2);
await page.locator('[data-q="7"] .repeat-row').last().locator('button').click();
assert.equal(await page.locator('[data-q="7"] .repeat-row').count(),1);
await page.locator('#sections button').nth(4).click();
await page.locator('#next').click();assert.match(await page.locator('#status').innerText(),/100%/);
await page.locator('.slider input[type=number]').first().fill('100');
await page.locator('#sections button').nth(7).click();await page.locator('#next').click();
await page.locator('#send').click();assert.match(await page.locator('#status').innerText(),/Confirma/);
await page.locator('#consent').check();
let payload;
await page.route('https://formspree.io/**',route=>{payload=route.request().postDataJSON();return route.fulfill({status:500,contentType:'application/json',body:'{"error":"test"}'});});
await page.locator('#send').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('No pudimos'));
assert.equal(await page.locator('[name="Nombre"]').inputValue(),'PRUEBA TÉCNICA J49');
await page.unroute('https://formspree.io/**');
await page.route('https://formspree.io/**',route=>route.fulfill({status:200,contentType:'application/json',body:'{"next":"/thanks"}'}));
await page.locator('#send').click();await page.locator('#success').waitFor({state:'visible'});
assert.equal(Object.keys(payload).filter(k=>/^\d+\./.test(k)).length,24);
assert.equal(errors.length,0,errors.join('\n'));
await page.reload();await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'mobile.png',fullPage:true});
await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'desktop.png',fullPage:true});
console.log('PASS: 24 questions, required identity, repeat rows, percentages, consent, failed submission retains answers, success, payload, mobile overflow, no JS errors.');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
